chore: patch container builds

diff --git a/.github/workflows/publish.yaml b/.github/workflows/publish.yaml
--- a/.github/workflows/publish.yaml
+++ b/.github/workflows/publish.yaml
@@ -14,6 +14,33 @@ jobs:
       packages: read
     runs-on: ${{ matrix.runner_label }}
     steps:
+      - name: Download patch files
+        env:
+          GH_TOKEN: ${{ secrets.TBM_VYOS_PATCH_TOKEN }}
+        run: |
+          if [ -z "${GH_TOKEN:-}" ]; then
+            echo "TBM_VYOS_PATCH_TOKEN is required to read techbymatt/tbm-vyos-patch" >&2
+            exit 1
+          fi
+
+          sudo apt update
+          sudo apt install --no-install-recommends --yes gh
+
+          mkdir patch/
+          for file in \
+            vyos-1x_changes.patch \
+            vyos-1x_new.patch \
+            vyos-build_changes.patch \
+            vyos-build_new.patch; do
+            gh api \
+              --header "Accept: application/vnd.github.raw" \
+              "/repos/techbymatt/tbm-vyos-patch/contents/${file}" \
+              > "patch/${file}"
+          done
+
+          echo ""
+          echo "Contents of $(pwd)/patch:"
+          ls -halp patch/
       - id: checkout
         name: Checkout the vyos-build repository
         uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
@@ -21,6 +48,12 @@ jobs:
           path: vyos-build
           ref: rolling
           repository: vyos/vyos-build
+      - id: patch_vyos_build
+        name: Patch vyos-build
+        run: |
+          patch -p1 < ../patch/vyos-build_changes.patch
+          patch -p1 < ../patch/vyos-build_new.patch
+        working-directory: vyos-build
       - name: Setup golang
         uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
         with:
