fix: disable split builds for kernel modules

diff --git a/.github/workflows/publish.yaml b/.github/workflows/publish.yaml
--- a/.github/workflows/publish.yaml
+++ b/.github/workflows/publish.yaml
@@ -57,27 +57,26 @@ jobs:
         uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
         with:
           go-version: "1.26.4"
-      - if: ${{ matrix.package != 'linux-kernel' }}
-        name: Build the package
+      - name: Build the package
         run: |
           sudo apt-get update
           python3 build.py
         working-directory: vyos-build/scripts/package-build/${{ matrix.package }}
-      - if: ${{ matrix.package == 'linux-kernel' }}
-        name: Build the package
-        run: |
-          sudo apt-get update
-          python3 build.py --packages linux-kernel
-        working-directory: vyos-build/scripts/package-build/${{ matrix.package }}
-      - if: ${{ matrix.package == 'linux-kernel' }}
-        name: Upload the kernel source artifact
-        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
-        with:
-          if-no-files-found: error
-          name: kernel-source-${{ matrix.arch }}
-          path: |
-            vyos-build/scripts/package-build/linux-kernel/kernel-vars
-            vyos-build/scripts/package-build/linux-kernel/*/linux
+      # - if: ${{ matrix.package == 'linux-kernel' }}
+      #   name: Build the package
+      #   run: |
+      #     sudo apt-get update
+      #     python3 build.py --packages linux-kernel
+      #   working-directory: vyos-build/scripts/package-build/${{ matrix.package }}
+      # - if: ${{ matrix.package == 'linux-kernel' }}
+      #   name: Upload the kernel source artifact
+      #   uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
+      #   with:
+      #     if-no-files-found: error
+      #     name: kernel-source-${{ matrix.arch }}
+      #     path: |
+      #       vyos-build/scripts/package-build/linux-kernel/kernel-vars
+      #       vyos-build/scripts/package-build/linux-kernel/*/linux
       - name: Upload the .deb files as artifacts
         uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
         with:
@@ -168,8 +167,7 @@ jobs:
           sudo apt-get update
           dpkg-buildpackage --build=binary --unsigned-changes --unsigned-source
         working-directory: packages/${{ matrix.package }}
-      - if: ${{ matrix.package != 'linux-kernel' }}
-        name: Upload the .deb files as artifacts
+      - name: Upload the .deb files as artifacts
         uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
         with:
           if-no-files-found: error
@@ -227,85 +225,85 @@ jobs:
           - deps: dh-virtualenv
             package: vyos-http-api-tools
     timeout-minutes: 10
-  build-modules:
-    container:
-      env:
-        TZ: Australia/Brisbane
-      image: ghcr.io/techbymatt/vyos-build:rolling
-      options: "--privileged --sysctl net.ipv6.conf.lo.disable_ipv6=0"
-    defaults:
-      run:
-        shell: bash
-    name: Build (modules)
-    needs: [build]
-    permissions:
-      packages: read
-    runs-on: ${{ matrix.runner_label }}
-    steps:
-      - name: Checkout the vyos-build repository
-        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
-        with:
-          path: vyos-build
-          ref: rolling
-          repository: vyos/vyos-build
-      - name: Download the kernel source artifact
-        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
-        with:
-          name: kernel-source-${{ matrix.arch }}
-          path: vyos-build/scripts/package-build/linux-kernel
-      - if: ${{ matrix.arch == 'amd64' || (matrix.arch == 'arm64' && !matrix.skip_arm64) }}
-        name: Build the module package
-        run: |
-          python3 build.py --packages ${{ matrix.module }}
-        working-directory: vyos-build/scripts/package-build/linux-kernel
-      - if: ${{ matrix.arch == 'amd64' || (matrix.arch == 'arm64' && !matrix.skip_arm64) }}
-        name: Upload the .deb files as artifacts
-        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
-        with:
-          if-no-files-found: error
-          name: deb-${{ matrix.module }}
-          path: |
-            vyos-build/scripts/package-build/**/*.changes
-            vyos-build/scripts/package-build/**/*.deb
-            vyos-build/scripts/package-build/**/*.dsc
-            vyos-build/scripts/package-build/**/*.tar.bz2
-            vyos-build/scripts/package-build/**/*.tar.gz
-            vyos-build/scripts/package-build/**/*.tar.xz
-    strategy:
-      fail-fast: false
-      matrix:
-        arch: [amd64, arm64]
-        module:
-          - accel-ppp-ng
-          - i40e
-          - iavf
-          - ice
-          - igb
-          - ipt-netflow
-          - ixgbe
-          - ixgbevf
-          - jool
-          - linux-firmware
-          - mlnx
-          - nat-rtsp
-          - qat
-          - realtek-r8126
-        include:
-          - arch: amd64
-            runner_label: ubuntu-24.04
-          - arch: arm64
-            runner_label: ubuntu-24.04-arm
-          - module:
-              - i40e
-              - iavf
-              - ice
-              - igb
-              - ixgbe
-              - ixgbevf
-              - mlnx
-              - qat
-            skip_arm64: true
-    timeout-minutes: 120
+  # build-modules:
+  #   container:
+  #     env:
+  #       TZ: Australia/Brisbane
+  #     image: ghcr.io/techbymatt/vyos-build:rolling
+  #     options: "--privileged --sysctl net.ipv6.conf.lo.disable_ipv6=0"
+  #   defaults:
+  #     run:
+  #       shell: bash
+  #   name: Build (modules)
+  #   needs: [build]
+  #   permissions:
+  #     packages: read
+  #   runs-on: ${{ matrix.runner_label }}
+  #   steps:
+  #     - name: Checkout the vyos-build repository
+  #       uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
+  #       with:
+  #         path: vyos-build
+  #         ref: rolling
+  #         repository: vyos/vyos-build
+  #     - name: Download the kernel source artifact
+  #       uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
+  #       with:
+  #         name: kernel-source-${{ matrix.arch }}
+  #         path: vyos-build/scripts/package-build/linux-kernel
+  #     - if: ${{ matrix.arch == 'amd64' || (matrix.arch == 'arm64' && !matrix.skip_arm64) }}
+  #       name: Build the module package
+  #       run: |
+  #         python3 build.py --packages ${{ matrix.module }}
+  #       working-directory: vyos-build/scripts/package-build/linux-kernel
+  #     - if: ${{ matrix.arch == 'amd64' || (matrix.arch == 'arm64' && !matrix.skip_arm64) }}
+  #       name: Upload the .deb files as artifacts
+  #       uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
+  #       with:
+  #         if-no-files-found: error
+  #         name: deb-${{ matrix.module }}
+  #         path: |
+  #           vyos-build/scripts/package-build/**/*.changes
+  #           vyos-build/scripts/package-build/**/*.deb
+  #           vyos-build/scripts/package-build/**/*.dsc
+  #           vyos-build/scripts/package-build/**/*.tar.bz2
+  #           vyos-build/scripts/package-build/**/*.tar.gz
+  #           vyos-build/scripts/package-build/**/*.tar.xz
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       arch: [amd64, arm64]
+  #       module:
+  #         - accel-ppp-ng
+  #         - i40e
+  #         - iavf
+  #         - ice
+  #         - igb
+  #         - ipt-netflow
+  #         - ixgbe
+  #         - ixgbevf
+  #         - jool
+  #         - linux-firmware
+  #         - mlnx
+  #         - nat-rtsp
+  #         - qat
+  #         - realtek-r8126
+  #       include:
+  #         - arch: amd64
+  #           runner_label: ubuntu-24.04
+  #         - arch: arm64
+  #           runner_label: ubuntu-24.04-arm
+  #         - module:
+  #             - i40e
+  #             - iavf
+  #             - ice
+  #             - igb
+  #             - ixgbe
+  #             - ixgbevf
+  #             - mlnx
+  #             - qat
+  #           skip_arm64: true
+  #   timeout-minutes: 120
   build-nocontainer:
     name: Build (no container)
     runs-on: ${{ matrix.runner_label }}
@@ -400,7 +398,7 @@ jobs:
     needs:
       - build
       - build-extra
-      - build-modules
+      # - build-modules
       - build-nocontainer
     permissions:
       id-token: write
